title: PIntron
subtitle: Gene-structure prediction based on spliced alignments of transcript sequences.
description: PIntron-A novel pipeline for gene-structure prediction based on spliced alignment of ESTs and mRNAs against a genomic sequence.

url: http://pintron.algolab.eu
root: http://pintron.algolab.eu
author: AlgoLab

github_repository: PIntron
github_user: AlgoLab
github_tags_count: 2

nav:
  - name: Home
    link: "index.html"
  - name: Installation
    link: "install.html"
  - name: Get started
    link: "example.html"
  - name: Documentation
    link: "documentation.html"
  - name: Credits
    link: "credits.html"

simple_search: http://google.com/search
google_analytics_tracking_id: UA-32216930-1
